Homepage
ankerx/art-school pull request #1
Opened 2022-08-24 01:16 UTC by ankerx

The first task done

2022-08-25 14:11 UTC, vickierose requested changes
some things need improvements

2022-08-25 14:11 UTC, vickierose commented on .circleci/config.yml
> +              only: homepage
it should be your main branch, not feature one, because we want to see the whole working app hosted

2022-08-25 14:11 UTC, vickierose commented on src/App.js
> +import { Routes, Route } from "react-router-dom";
order of imports: the best practice is to put all the libraries imports on top and then internal imports: components, helpers, api-call functions, etc. And also good thing, especially if you import a lot of things, is to split each block with empty line so it was easier to read

2022-08-25 14:11 UTC, vickierose commented on src/index.css
> +@import url('https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700&display=swap');
why don't go with scss instead of pure css? it's more common in development nowadays and has a lot of powerful features (styles structure, mixins, functions, etc.)

2022-08-25 14:11 UTC, vickierose commented on src/index.css
> +  color: black;
for colors it's better to use hex codes and keep all colors in variables

2022-08-25 14:11 UTC, vickierose commented on src/modules/home/Main/Main.js
> +import { SubscribeSection } from "../Sections/Subscribe/SubscribeSection";
to shorten import paths it's better to have such component folder structure: 
`Hero` - folder
`HeroSection.js` or `Hero.js` - component itself
`index.js` - file that imports HeroSection component and exports it as default
`styles.(s)css` - styling file if necessary

this way you will just have
`import HeroSection from "../Sections/Hero"`

2022-08-25 14:11 UTC, vickierose commented on src/modules/layout/Footer/Footer.js
> +              <a href="/">{route}</a>
in React if we are not going to some other website we use `Link` or `NavLink` components

2022-08-25 17:21 UTC, ankerx commented on .circleci/config.yml
> +              only: homepage
I'm aware of that but I was making changes on the homepage branch, after the merge I was going to change it

2022-08-29 11:53 UTC, vickierose requested changes

2022-08-29 11:53 UTC, vickierose commented on src/App.js
> +import { Main } from "./modules/home/Main/Main";
a bit redundant. What I meant is libraries imports - empty line - ui components - empty line - api functions, redux imports, helpers - empty line. E.g. from my current project:

![Screenshot_43](https://user-images.githubusercontent.com/24248374/187193357-33c88c18-2ffb-45f2-8b4a-281c49525424.png)

2022-08-29 11:53 UTC, vickierose commented on src/App.js
> +import { Main } from "./modules/home/Main/Main";
check order and grouping of imports in all files, please

2022-08-29 11:53 UTC, vickierose commented on src/modules/home/components/Button/Button.js
> +    <button>
wrapping link into button is redundant. They both are interactive elements and wrapping one into another is really bad idea. If you need button's styling on the link just apply the className

2022-08-29 13:32 UTC, ankerx commented on src/App.js
> +import { Main } from "./modules/home/Main/Main";
Ohh okay, I misunderstood

2022-08-30 11:26 UTC, vickierose requested changes

2022-08-30 11:26 UTC, vickierose commented on src/modules/apply/Apply.js
> +import { Heading } from "./components/Heading";
put import in correct order: libraries > components > other

2022-08-30 11:26 UTC, vickierose commented on src/modules/apply/components/LabelWithInput.js
> +      <input {...register(name)} className={styles.input} placeholder="hello" />
I guess here instead of "hello" should be `placeholder={placeholder}`

2022-08-31 15:12 UTC, vickierose approved these changes

2022-08-31 22:48 UTC, merged